name: Build & Push Docker Image to Amazon ECR using AWS OIDC IAM role
on:
  push:
    branches:
      - "master"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout ml-common repo
        uses: actions/checkout@v3
        with:
           repository: flutter/samples.git
           ref: main
      - name: Clone repository
        run: git clone https://github.com/flutter/samples.git
      - name: Upload artifactBuild
        uses: actions/upload-artifact@master
        with:
           path: add_to_app

  
  build-on-work-branch:
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - name: Download artifact 
      uses: actions/download-artifact@master
      with:
        name: 
        path: 

        run: ls -alt add_to_app

   
